# 模拟日志生成器配置
mock.max.mall=10
mock.category=100
mock.sku=1000
mock.user=1000
mock.payment=5
mock.order.count.per.day=1000
mock.pageview.count.per.day=5000
mock.cart.count.per.day=500
mock.favor.count.per.day=200
mock.if_delayed.create.order=0
mock.if_delayed.payment=0
mock.if_delayed.cancel.order=0
mock.timeout=5
mock.log.path=/opt/module/applog/log
